select * from customer limit 20
--QUESTIONS 1 TO 10
--1. What is the total revenue generated by Male VS. Female Customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--2. WHich Customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4. Compare the average purchase amounts between standard and express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers
select subscription_status,
COUNT (customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--6. Which 5 products have the highest percentage of purchases with discount applied?


